version: "3.7"

networks:
  net-api:
    driver: bridge

services:
  globalweb:
    image: globalweb
    depends_on:
      - postgres
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: 0.1 - Presentation/GlobalWeb.API/Dockerfile
    container_name: globalwebapi
    environment:
      DB_CONNECTION: "Host=postgres;Port=5432;Database=db;Username=admin;Password=123"
    restart: on-failure
    networks:
      - net-api

  postgres:
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    container_name: "postgres"
    restart: always
    volumes:
      - ./postgres:/var/lib/data
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    networks:
      - net-api

volumes:
  postgres:

    